import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const nunitoSans = Nunito_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Our Cool App",
  description: "Generated by fullstak",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.variable} ${geistMono.variable} antialiased`}>
          <main className="bg-gray-100 min-h-screen flex flex-col items-center">
            <nav className="w-full bg-white h-16 flex items-center justify-center">
              <section className="container flex items-center gap-3" >
                <Image src='/logo.jpg' alt="logo" width={48} height={48}/>
                <h1 className="font-bold text-2xl">Countries App</h1>
              </section>
            </nav>
          </main>
        {children}
      </body>
    </html>
  );
}
